apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kn-backend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kn-backend
    app.kubernetes.io/part-of: kn-backend
  name: kn-backend
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kn-backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kn-backend
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/ldary24-tenant/kn-backend/kn-backend@sha256:73999eb06dc3fd31df1e3698c8c2f43ee92da7a13493ee80c918e54e1a7f5304
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
